agents:
  queue: new-central
  slurm_mem: 8G
  modules: climacommon/2024_12_16

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1

steps:
  - label: "initialize"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate buildkite"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_mem: 10G
      slurm_gpus: 1
      slurm_cpus_per_task: 2
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 12

  - wait

  - group: "Unit: Package-wide"
    steps:

      - label: "Unit: aqua"
        key: unit_aqua
        command: "julia --color=yes --check-bounds=yes --project=.buildkite test/aqua.jl"

